### ISSUE TITLE
Temario Dominicode LiveCoding 23-08-2020

### ISSUE THREAD

**Issue by ruslanguns** [ruslanguns/nestjs-myblog#1]
- [x] **Creación del repositorio**

> - Clonar repositorio 
`git clone -b livecoding/1 https://github.com/ruslanguns/nestjs-myblog.git myblog`

- [x] **Creacion de CRUD de usuario**

### Requisitos:
**Paquetes:**
```
- bcryptjs
- @types/bcryptjs
```

> - Creación de estructura de usuario (archivos con el CLI)
> - Creando la configuración de la entidad de usuario
> - Configurando los DTOs de Usuario
> - Inyectando el repositorio en el provider de Usuario y creando el CRUD
> - Ajustar los nombres de camelCase a pascal_case para las propiedades de la DB
> - Encriptar contraseña y ocultándola en las peticiones: [FUENTE](https://stackoverflow.com/questions/50360101/how-to-exclude-entity-field-from-returned-by-controller-json-nestjs-typeorm?rq=1)

- [x] **Configuración para usar los ENV con el paquete @nestjs/config**

### Requisitos:
**Paquetes:**
```
- @nestjs/config
```
> - Inyección de ConfigModule y configuración del archivo .env
> - Implementar variables de entorno con el TypeORM de forma asíncrona
> - Evitar los [Magic Strings](https://softwareengineering.stackexchange.com/questions/365339/what-is-wrong-with-magic-strings) y hacer uso de constantes
> - No nos olvidemos de crear un SAMPLE ENV y excluirlo del GIT

- [ ] **Implementando la autenticación de usuarios**
### Requisitos:
**Paquetes:**
```
# LOCAL STRATEGY
- @nestjs/passport
- passport
- passport-local
- @types/passport-local (DEV)

# JWT STRATEGY
- @nestjs/jwt
- passport-jwt
- @types/passport-jwt (DEV)
```

> - Estructura de carpetas que usaremos.
> - Configuración básica siguiendo la [Documentacion oficial](https://docs.nestjs.com/techniques/authentication#implementing-passport-strategies)
> - Inyectar PassportModule
> - Crear el provider localStrategy e implementarlo conjunto al servicio
> - Mi primer Custom Decorator para obtener el usuario
> - Inyectar JwtModule
> - Implementar el provider jwtStrategy e implementarlo
> - Método de Login JWT y endpoint profile
> - Error handling con JWT en el Guard
> - Configuración para el Swagger addBearerAuth()

- [ ] **Gestionar los Roles con el paquete nest-access-control**

### Requisitos:
**Paquetes:**
```
- nest-access-control
```
> - Modificación de UserModel para almacenar los roles
> - Creación del archivo app.roles.ts y utilizar builder
> - Inyectar el AccessControlModule en el AppModule
> - Creación del decorador wrapper
> - Implementar lógica de negocio para rutas OWN && ANY
> - Creación de una función para generar un usuario único

- [ ] **Recomendaciones de seguridad, [docs](https://docs.nestjs.com/techniques/security)**

### ROADMAP 

- [En Imagen](https://user-images.githubusercontent.com/19806968/90977794-25056680-e540-11ea-85dd-5851d58aaef5.png)

  |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Controller | Método | Ruta | Info | PUBLIC | AUTHOR | ADMIN | AUTHOR   POSSESION | ADMIN   POSSESION |  
  | USER | GET | /user | Get Many | YES | YES | YES | ANY | ANY |  
  | USER | GET | /user/1 | Get One By ID | YES | YES | YES | ANY | ANY |  
  | USER | POST | /user | Create One | NO | YES | YES | OWN | OWN |  
  | USER | PUT | /user/1 | Edit One | NO | YES | YES | OWN | ANY |  
  | USER | DELETE | /user/1 | Delete One | NO | YES | YES | OWN | ANY |  
  | USER | POST | /post | Registration | YES | YES | YES | - | - |  
  | POST | GET | /post | Get Many | YES | YES | YES | ANY | ANY |  
  | POST | GET | /post/1 | Get One By ID | YES | YES | YES | ANY | ANY |  
  | POST | POST | /post | Create One | NO | YES | YES | OWN | OWN |  
  | POST | PUT | /post/1 | Edit One | NO | YES | YES | OWN | ANY |  
  | POST | DELETE | /post/1 | Delete One | NO | YES | YES | OWN | ANY |  
  | AUTH | POST | /auth/login | Login | YES | YES | YES | - | - |  
  | AUTH | GET | /auth/profile | Get me | NO | YES | YES | - | - |  
  |   |   |   |   |   |   |   |   |   |  

## Articles to read
- https://medium.com/better-programming/getting-started-with-nestjs-a4e8b0b09db4
- https://medium.com/@sureshdsk/how-json-web-token-jwt-authentication-works-585c4f076033
- https://docs.nestjs.com/techniques/security#csrf
- https://codeburst.io/why-you-should-use-nestjs-for-your-next-project-6a0f6c993be
- https://auth0.com/blog/modern-full-stack-development-with-nestjs-react-typescript-and-mongodb-part-1/
- https://cutt.ly/Lfo6d5f

**Comment by bezael** [comment]
Eres un crack!

**Comment by aurelio-mont** [comment]
Eres buenicimo, saludos desde México

**Comment by femastro** [comment]
me contacte con el en privado y la verdad , un maestro !!!! GRACIAS!!!! Ruslan!!!

**Comment by femastro** [comment]
estoy empezando con todo esto, estuve viendo como usar Git, creo que lo hice bien, pase un commit. con lo que te comente. del .env.sample.   si hice lio o algo mal decirme.

**Comment by ruslanguns** [comment]
Excelente! ¡Estate pendiente de la próxima entrega! ¡Saludos!

--
Ruslán González
Tel: +34 644 27 47 56
email: ruslanguns@gmail.com

**Comment by femastro** [comment]
no no puede porque no estoy autorizado para hacer un commit.

**Comment by femastro** [comment]
bueno menos mal no hice lio..

**Comment by ruslanguns** [comment]
@femastro no nada mal hecho, tranqui! El domingo la próxima parte del mini curso!

**Comment by ruslanguns** [comment]
Cierro este Issue y abro #4 para continuar con la parte II de este hilo.
